# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Crawler.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.keyword_label = QtWidgets.QLabel(self.centralwidget)
        self.keyword_label.setGeometry(QtCore.QRect(60, 20, 50, 30))
        self.keyword_label.setObjectName("keyword_label")
        self.num_label = QtWidgets.QLabel(self.centralwidget)
        self.num_label.setGeometry(QtCore.QRect(70, 60, 40, 30))
        self.num_label.setObjectName("num_label")
        self.save_address_label = QtWidgets.QLabel(self.centralwidget)
        self.save_address_label.setGeometry(QtCore.QRect(50, 100, 65, 30))
        self.save_address_label.setObjectName("save_address_label")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(120, 180, 100, 30))
        self.submit_button.setObjectName("submit_button")
        self.log_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.log_edit.setGeometry(QtCore.QRect(230, 10, 501, 201))
        self.log_edit.setObjectName("log_edit")
        self.keyword_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword_edit.setGeometry(QtCore.QRect(120, 20, 100, 30))
        self.keyword_edit.setText("")
        self.keyword_edit.setObjectName("keyword_edit")
        self.num_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.num_edit.setGeometry(QtCore.QRect(120, 60, 100, 30))
        self.num_edit.setText("")
        self.num_edit.setObjectName("num_edit")
        self.save_address_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.save_address_edit.setGeometry(QtCore.QRect(120, 100, 100, 30))
        self.save_address_edit.setText("")
        self.save_address_edit.setObjectName("save_address_edit")
        self.pic_load_label = QtWidgets.QLabel(self.centralwidget)
        self.pic_load_label.setGeometry(QtCore.QRect(50, 140, 65, 30))
        self.pic_load_label.setObjectName("pic_load_label")
        self.pic_load_button = QtWidgets.QPushButton(self.centralwidget)
        self.pic_load_button.setGeometry(QtCore.QRect(120, 140, 100, 30))
        self.pic_load_button.setObjectName("pic_load_button")
        self.get_proxies_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_proxies_button.setGeometry(QtCore.QRect(630, 220, 100, 30))
        self.get_proxies_button.setObjectName("get_proxies_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(120, 220, 100, 30))
        self.stop_button.setObjectName("stop_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.keyword_label.setText(_translate("MainWindow", "关键词"))
        self.num_label.setText(_translate("MainWindow", "数量"))
        self.save_address_label.setText(_translate("MainWindow", "保存地址"))
        self.submit_button.setText(_translate("MainWindow", "submit"))
        self.pic_load_label.setText(_translate("MainWindow", "以图搜图"))
        self.pic_load_button.setText(_translate("MainWindow", "上传图片"))
        self.get_proxies_button.setText(_translate("MainWindow", "更新ip池"))
        self.stop_button.setText(_translate("MainWindow", "停止"))
